server:
  port: 8001


spring:
  application:
    name: cloud-payment-8001 #微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSl=false
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.usst.springcloud.pojo